### ISSUE TITLE
Double Dragon & Double Dragon II MIST cores don't boot

### ISSUE THREAD

**Issue by jegayon** [jotego/jtbin#102]
I have tried two MIST cores with the same result. When boot up, the MIST hungs up and NO OSD activity. I can't reset the MIST, only turn power off.
ROM build with correct 0216 romset.

Thx for all your work and effort.

**Comment by jotego** [comment]
You need the latest firmware and you must also generate the ARC files using the mra tool.

**Comment by jegayon** [comment]
Hi José.
I just updated the MIST firmware and it worked like a charm. Now I have noticed that the firmware was too old :(
Now I am going to generate the ARC files of the DD's with the MRA tool.
Thanks a lot. :)
