### ISSUE TITLE
Popeye - VGA outputs no game, can see yellow menu

### ISSUE THREAD

**Issue by thepulserifle** [jotego/jtbin#11]
When outputting to VGA--> Component, Popeye does not display. The menu can be pulled up, but there is no game screen showing on the CRT whatsoever.

**Comment by goldenegg** [comment]
I have the same issue, going VGA -> RGB to a Sony PVM-1340.  The game is loading, as you can start the game and hear audio.  

If I enable the VGA scaler in MiSTer, I can get an image, but it's unplayable since the scaler can't provide an appropriate resolution for the CRT.

**Comment by jotego** [comment]
Popeye is currently not maintained as another core for the arcade emerged.
