### ISSUE TITLE
[MIST] Bubble Bobble image centering issue.

### ISSUE THREAD

**Issue by squidrpi** [jotego/jtbin#124]
On the MiST, image is shifted to the right on Bubble Bobble & Black Tiger.

**Comment by jotego** [comment]
Do you see that on a 15kHz CRT?

**Comment by squidrpi** [comment]
Yes

**Comment by jotego** [comment]
I had a CRT centering feature on mister cores that couldn't use on mist before. But a recent change in the mist firmware has open the door to supporting this too. I will add a CRT image centering feature to all cores in mist too.

**Comment by jotego** [comment]
Fixed in 335ab4d
