### ISSUE TITLE
Bubble Bobble MRA file wrong rom?

### ISSUE THREAD

**Issue by squidrpi** [jotego/jtbin#127]
Shouldn't the rom set be bublbobl instead of bublboblr? Bublbobr also defaults to Japanese and adds the Super Game option. Can't see a way in the MRA creation to choose.

**Comment by jotego** [comment]
The names for ROM sets are extracted directly from MAME with an automatic tool, so the MRA file should be ok.

The Japanese/English version is actually selected via DIP switches.

I don't know what you mean by "Super Game"

**Comment by squidrpi** [comment]
bublboblr is a clone of bublbobl with "with mode select". When you start a game you can choose the original game or "Super Game" - this isn't in the original Bubble Bobble.

**Comment by squidrpi** [comment]
Fixed thanks!
