### ISSUE TITLE
CPS1 credit mapped to Player 2

### ISSUE THREAD

**Issue by owlnonymous** [jotego/jtbin#13]
CPS1 credit mapped to Player 2
Coin button pauses game
Can't get ghouls to boot.

**Comment by paulb-nl** [comment]
Yea same. I have to use the buttons 5 and 1 on the keyboard for credit and 1p start.

**Comment by rarcos** [comment]
Seems fixed with 0226 release

**Comment by jotego** [comment]
Fixed.
