### ISSUE TITLE
Side Arms: no sound on MiST

### ISSUE THREAD

**Issue by gyurco** [jotego/jtbin#131]
The released binary has no sound on MiST. Also the date is suspicious: jtsarms_20200814.
I've just recompiled it, and it's OK. Noticed that the rbf size is also considerably larger with sound (320k vs 260k).

**Comment by jotego** [comment]
Thank you. I must have recompiled without sound on the same day and overwritten the file.
I have fixed it now :-)

**Comment by gyurco** [comment]
Thanks! You're a machine releasing new cores constantly :)
