### ISSUE TITLE
Street Fighter on MiST

### ISSUE THREAD

**Issue by veb-xenon** [jotego/jtbin#137]
I'm using Street Fighter on MiST. 

First, I get this error when creating the ARC

![imagen](https://user-images.githubusercontent.com/62928707/100660328-2bcb2300-3352-11eb-8c24-d5cb00a6ee10.png)

Then .ARC and .ROM are created. Game starts, but voices and digital effects are too "dirty" and sound really bad Also, only two countries appear in the select screen, and not four, no switch appears, and it's available on emulation:

![imagen](https://user-images.githubusercontent.com/62928707/100660716-b449c380-3352-11eb-9a7f-86e271ab4006.png)

And finally, Coin B switch does not work well, and it's linked with "Show Credits" option.

Thanks for your work!

**Comment by jotego** [comment]
Please check today's update. ADPCM voices are almost perfect now.
I have also added an unfiltered video output mode.
As for ARC files, I think I need a bit of help from the community to handle all ARC/MRA files. It is something rather easy, so I accept pull requests for it in this repository.
