### ISSUE TITLE
CPS1.5: Address error in Muscle Bomber Duo

### ISSUE THREAD

**Issue by SegaSnatcher** [jotego/jtbin#139]
I keep getting an address error while playing Muscle Bomber Duo.

![unnamed (4)](https://user-images.githubusercontent.com/36483667/101955109-d3521c00-3bc2-11eb-9f2c-44ff1b6611dc.jpg)

**Comment by jotego** [comment]
I am sorry about that. I think this is the same as #140 so I am closing it here.
