### ISSUE TITLE
CPS1 analog video output shift

### ISSUE THREAD

**Issue by paulb-nl** [jotego/jtbin#14]
The video on a 15Khz CRT is shifted right about 25 pixels. This is on MiSTer.

**Comment by edru** [comment]
Same issue here.

**Comment by mpjedi** [comment]
me too

**Comment by paulb-nl** [comment]
Thanks for adjusting. Version 0226 is now shifted about 5 pixels too far to the left. Also it should be lowered about 4 lines.

**Comment by paulb-nl** [comment]
Somewhat related: The internal video is shifted right by 2 pixels. There are 2 black pixels on the left in this screenshot made by the MiSTer screenshot feature.
![ffight_shift](https://user-images.githubusercontent.com/2227984/75385876-eec49280-58e0-11ea-8da0-1410268ad5d6.png)

**Comment by jotego** [comment]
Thank you for that screenshot. It is a good indicator of the horizontal blanking being off.

**Comment by paulb-nl** [comment]
Version 0306:
A little bit too far to the right now. Still needs to be lowered a few lines.
Hblank shift is fixed.

**Comment by paulb-nl** [comment]
The vertical position is perfect with 0418 but the horizontal position was better centered with 0417.

**Comment by jotego** [comment]
I think this is fixed now

**Comment by paulb-nl** [comment]
Thanks Jose. I recommend making Horizontal +5 the default 0 position because that is perfectly centered compared to consoles on the same CRT like SNES, Genesis and PC Engine. I also saw Andrew Moore use +5 in his latest CPS1 video.

**Comment by paulb-nl** [comment]
With version 0515 it seems you have adjusted the horizontal position the wrong way. Now it needs more than +7 to center.
