### ISSUE TITLE
Saturday Night Slam Masters hangs up afterfight

### ISSUE THREAD

**Issue by jotego** [jotego/jtbin#144]
An illegal instruction message shows. This can be replicated with 32MB/128MB modules and on MiST so I do not think it is related to the SDRAM.

![20201213_075520-screen](https://user-images.githubusercontent.com/1863036/102006501-db749d80-3d21-11eb-932d-5563b8d703aa.png)

**Comment by SegaSnatcher** [comment]
Using latest CPS 1.5 96Mhz release I do not get this error anymore.  I was able to play through many matches with no issues.

**Comment by odiaboeeu** [comment]
Yes, Yesterday I managed to finish without any error in this latest version of the core that Jotego released 😇🙏

**Comment by jotego** [comment]
I think this has got fixed accidentally, or maybe this was a manifestation of an SDRAM problem that is less sensitive in this release. I need to check the changelogs to make sense of this.
