### ISSUE TITLE
CPS1 Ghouls scroll y? no good

### ISSUE THREAD

**Issue by Aquas77** [jotego/jtbin#15]
on 32mb xs1.1 sdram sorg, used latest romset for ghouls, notest version.. regular version  i can potentially test 64mb at some point...
![20200223_081550-screen](https://user-images.githubusercontent.com/53416049/75106551-7f4e5a80-55e3-11ea-8e3f-fd1ca61c34b2.png)

I noticed that the intro sequence will run on fresh boot but will then crash to scroll error as gameplay is about to kick in during the attract sequence. The regular ghouls mra didn't boot

**Comment by cacophony1** [comment]
I get a similar crash screen after ~45 seconds into a play session. I'm using 128MB sdram module and the _notest.mra (because I couldn't get past initial test sequence with regular mra)

**Comment by Aquas77** [comment]
Issue fixed with the new rbf version 20200223

**Comment by jotego** [comment]
Thank you
