### ISSUE TITLE
Illegal Instruction on SF0 (CPS 1.5)

### ISSUE THREAD

**Issue by kaloun34** [jotego/jtbin#154]
I have an error with SF0 if I let the demo play by itself after a few minutes
![20201223_084016-screen](https://user-images.githubusercontent.com/54940754/102972572-8b54c280-44fb-11eb-8b36-0b942e030110.png)

is it also because of a memory module 128 problem?

**Comment by jotego** [comment]
Please try today's update and fill the poll here:
https://www.patreon.com/posts/45683205

**Comment by kaloun34** [comment]
same problem with the latest version
