### ISSUE TITLE
jtcps15 feedback per version / per game

### ISSUE THREAD

**Issue by Saroumane** [jotego/jtbin#155]
Hello,
 I remember a few weeks ago I had "Saturday Night Slam Masters" running in attract mode for about an hour without problem.
I can't reproduce that with latest jtcps15 core. So I decided to re-test all versions. 
Full disclaimer : I have an 128 MB "2 chips" module.

### EDIT : new try with jtcps15_20201219.rbf
I read some people had better results after powering off, and letting the MiSTer cool down.
So did I, and I put the fan to its max speed.
The results are better :

- 'Muscle Bomber Duo Ultimate Team Battle (World 931206).mra'
boot normally, played 5 min without problem.
Attract mode now can run for more than 15 min without errors, even if this game is not the 1st game launched on MiSTer since power on.

- 'Saturday Night Slam Masters (World 930713).mra'
boot on blue title screen, then black screen. Maybe a ROM problem ?
I checked /media/fat/games/slammast.zip vs the mra file : every file is here and their CRC are OK. It's a mistery for me...

- 'The Punisher (World 930422).mra'
Played 15 min without problem, reached 3rd boss.
If The Punisher is not  the 1st game  launched since MiSTer power on, "Attract mode"  will hang early (on screen "Based upon Characters appearing in ...")

- 'Warriors of Fate (World 921031).mra'
Attract mode has run for 210 min without problem.
Playing : Still crashing.... but a bit later, in the middle of the 2nd level or at 2nd level boss.
=> Is it expected, even for "safe" memory modules users ?

### jtcps15_20201219.rbf

- 'Cadillacs and Dinosaurs (World 930201).mra'
**Finished all 8 levels of the game without crash.
No problem in attract mode.** 
A bit of "tearing" in the upper part of the screen when dashing after having cleared a wave. 
I don't know if original board does the same.

- 'Muscle Bomber Duo Ultimate Team Battle (World 931206).mra'
black screen

- 'Saturday Night Slam Masters (World 930713).mra'
black screen

- 'The Punisher (World 930422).mra'
black screen or crash after 5min playing

- 'Warriors of Fate (World 921031).mra'
Crash at 1st boss

### jtcps15_20201218.rbf

- 'Cadillacs and Dinosaurs (World 930201).mra'
Crash with illegal instruction after 2min playing

- 'Muscle Bomber Duo Ultimate Team Battle (World 931206).mra'
black screen

- 'Saturday Night Slam Masters (World 930713).mra'
black screen

- 'The Punisher (World 930422).mra'
black screen

- 'Warriors of Fate (World 921031).mra'
Crash at character select

### jtcps15_20201212.rbf

- 'Cadillacs and Dinosaurs (World 930201).mra'
black screen

- 'Muscle Bomber Duo Ultimate Team Battle (World 931206).mra'
black screen

- 'Saturday Night Slam Masters (World 930713).mra'
black screen

- 'The Punisher (World 930422).mra'
crash at boot with "adress error"

- 'Warriors of Fate (World 921031).mra'
Crash mid-level before 1st boss

### jtcps15_20201211.rbf

- 'Cadillacs and Dinosaurs (World 930201).mra'
Crash after 2min playing

- 'Muscle Bomber Duo Ultimate Team Battle (World 931206).mra'
black screen

- 'Saturday Night Slam Masters (World 930713).mra'
black screen

- 'The Punisher (World 930422).mra'
crash at boot with "adress error"

- 'Warriors of Fate (World 921031).mra'
Crash at 1st boss

**Comment by Saroumane** [comment]
I also read that the game "Street Fighter Zero (CPS 1.5 QSound Hack)" is a good test.

From MiSTer switched off (for a long time) , 
1. I power on and launch the game "Street Fighter Zero (CPS 1.5 QSound Hack)"
2. I play a few rounds (5min), then let the attract mode run for 70 min : no problem at all
3. Then "cold reboot" (via MiSTer menu), launch NeoGeo core, boot Samurai Showdown 5
4. Then **"cold reboot" (via MiSTer menu)**, launch again "Street Fighter Zero (CPS 1.5 QSound Hack)" in attract mode : illegal instruction in the first demo round
5. I **reboot with a physical button** on the MiSTer and launch again "Street Fighter Zero (CPS 1.5 QSound Hack)" in attract mode : illegal instruction appears almost immediately, before the 1st round
6. I power-off, **wait 10 seconds**, power on, and launch "Street Fighter Zero (CPS 1.5 QSound Hack)" in attract mode : illegal instruction appears a few seconds later, during 1st demo round.
7. I power-off, **wait 70 seconds**, power on, and launch "Street Fighter Zero (CPS 1.5 QSound Hack)" in attract mode : same result than step 6
8. I power-off, **wait 5 min**, power on, and launch "Street Fighter Zero (CPS 1.5 QSound Hack)" in attract mode for 10min : no problems at all.

I don't know what to think.
Does it prove that 
- "cold reboot" is not cold enough ? 
- my SDRAM is faulty ?
- my cooling system is not enough ?
- A mix of these reasons ?

**Comment by jotego** [comment]
Thank you for the detailed report. Please try today's update and fill the poll here:
https://www.patreon.com/posts/45683205

**Comment by Saroumane** [comment]
You did magic, new core is correcting every problem I listed. (So I don't have to buy to new SDRAM... for now :)
