### ISSUE TITLE
ADDRESS ERROR on Cadillacs and Dinosaurs (64 MB SDRAM) 

### ISSUE THREAD

**Issue by Polo2018** [jotego/jtbin#156]
After playing for about 20mn on Cadillacs and Dinosaurs, the game froze but the music continued to play.
This message was on the screen : ADDRESS ERROR (see screen shot). 
My MiSTer has a 64 MB SDRAM board. 
![IMG_20201228_192344_compress77](https://user-images.githubusercontent.com/76710468/103247661-f2dd9880-4967-11eb-9f60-7b62f22220cf.jpg)

**Comment by Polo2018** [comment]
I played Cadillacs again today. And the game crashed exactly at the same place with exactly the same message (and same memory adresses) :
ADDRESS ERROR 
000D0D79
0001424C

The crash took place about 16 minutes after starting the game. I'm more sure about the time now (I used a chronometer). 

![IMG_20201229_163555_compress11](https://user-images.githubusercontent.com/76710468/103295505-64fbbf00-49f4-11eb-8eb9-697d4cb9000f.jpg)

**Comment by Polo2018** [comment]
I played Cadillacs a third time. 

The game crashed after about 7mn of playing. 

It's not the same place as before but it's the same message (and the same memory adresses) :
ADDRESS ERROR
000D0D79
0001424C

![IMG_20201229_172339_compress67](https://user-images.githubusercontent.com/76710468/103298868-844a1a80-49fb-11eb-933d-aa61b5486223.jpg)

**Comment by jotego** [comment]
The 64MB module is also prone to these problems. Not as much as the 128MB module, though.
Please try today's update and fill the poll here:
https://www.patreon.com/posts/45683205

**Comment by Polo2018** [comment]
With the latest core update jtcps15_20210102.rbf, for Cadillacs and Dinosaurs and The Punisher games, the issue is now a black screen. Even the warning page from Capcom doesn't appear.
