### ISSUE TITLE
Illegal Instruction on SF0 (CPS 1.5) 

### ISSUE THREAD

**Issue by kaloun34** [jotego/jtbin#161]
Hello

I have the same issue with the latest version but more quickly.
I also have a similar issue with "Saturday .." and a black screen with "Cadillac..."

![image](https://user-images.githubusercontent.com/54940754/103458689-d300f880-4d0a-11eb-8ae3-56a6b1e6e11c.png)

Best regards

**Comment by jotego** [comment]
Same as #162. Closing here as duplicated.
Please contact your RAM seller. There is little more I can do.
