### ISSUE TITLE
sound issues on cps1 latest release

### ISSUE THREAD

**Issue by mdd45** [jotego/jtbin#166]
On 15012021 cps1 release there are cracking noises on games like Final Fight Street Fighter 2 and CE. I havent tested any other games yet. Please check the sound of the barrels breaking in Final Fight intro and also the sounds of hitting especially on special moves in sf games.

**Comment by jotego** [comment]
I have recorded this at 192kHz/24 bit from the optical output. 
https://soundcloud.com/user-14108471/final-fight-20210115
It sounds good to me.

**Comment by mdd45** [comment]
Please listen carefully again at 0:19 there is cracking-noise. Maybe you should use other speakers or headset for more detail.

**Comment by odiaboeeu** [comment]
If using headphones you can really hear this problem, in sf2 it also happens a few times in the score of points when finishing a fight

**Comment by MJY71** [comment]
With the stage music in the Street Fighter II series for example (any of them), every time the kick drum hits, it sound like a tambourine taped to the back of a bass drum. There is ringing/jingling attached to the sound of that one particular instrument that should not be there.

The rest of the audio is absolutely amazing though. Vastly improved sound quality.

**Comment by jotego** [comment]
For reference: https://www.youtube.com/watch?v=diceCvElGB0

**Comment by pacoarcade** [comment]
I agree with mdd45. That youtube video linked sounds fine.

**Comment by mdd45** [comment]
With latest release jtcps1_20210117.rbf and the new available sound options, i think the issue has been fixed. Jotego thank you for the updates and efforts.
