### ISSUE TITLE
scanlines not working on latest release

### ISSUE THREAD

**Issue by mrfpga** [jotego/jtbin#169]
The scanlines from the menu (scandoubler fx, not custom filters) are no longer working on the latest release of the CPS1 core. I tested this with Street Fighter II Hyper Fighting.

Also there is a flickering line on the top left of Guile's stage.

**Comment by jotego** [comment]
Sorry, I updated the MiSTer firmware and many signals changed. I missed the changes for the scan lines signal.

I will upload it fixed in a couple of hours.
