### ISSUE TITLE
CPS1 - Final Fight - Horizontal video glitches

### ISSUE THREAD

**Issue by onegoodsoul** [jotego/jtbin#17]
Immediately in Final Fight, there is some horizontal graphical glitching. Using 32 MB SDRAM module.

**Comment by ctafield** [comment]
I think this one is fixed in the release from 6th March? (Seems to be for me anyway)

**Comment by M-Walrus** [comment]
i see this occur when many characters are onscreen at the same time. using the 3-13-20 build

**Comment by jotego** [comment]
Yes, I know the fix but it takes some rework. I may pospone it till later
development stages.

**Comment by jotego** [comment]
Fixed in 202003**27** version
