### ISSUE TITLE
CPS1 : Knights of the Round - Black pixel presents in the begining of the second stage

### ISSUE THREAD

**Issue by wwark** [jotego/jtbin#170]
You can see it at the right of Lancelot in this screenshot,
![20210117_103321-screen](https://user-images.githubusercontent.com/469461/104839388-1178e480-58c1-11eb-8a60-487a39ac752d.png)

Or under G of "GO" in this screenshot "thanks @Funkycochise",
![unknown](https://user-images.githubusercontent.com/469461/104839406-379e8480-58c1-11eb-9c43-da1a8294e876.png)

This black pixel moved when you moved Lancelot. Sometimes we have more than one.

I check this YT video using a PCB (visible at the beginning of the video)  and it is doesn't seem present
https://www.youtube.com/watch?t=296

The black pixel is present on those versions 96MHZ and 48MHZ of CPS1 core.

Thanks,

**Comment by jotego** [comment]
There is a good chance this is a ROM dump issue. Strider has a similar artifact in one of the main character sprites. I tracked it down and it was just stored like that in the graphics ROM.
We could patch the ROM.

**Comment by wwark** [comment]
Thanks for your return.
Did you inform Mame regarding the similar issue for Strider ?

**Comment by jotego** [comment]
Not really. They have a GitHub account too and I have entered issues but not this one.

**Comment by wwark** [comment]
Yesterday, I tested "Knights of the Round" on Mame and the black sprite are present.
Do you have a screenshot of black sprite on Strider ?
I will report those cases to Mame.

**Comment by jotego** [comment]
If you look in the issues here you will find it. Look for Strider and deselect the option "is open" in the search box. 
I think they need to mark the ROM dump as bad.

**Comment by wwark** [comment]
Thank you for your time !
