### ISSUE TITLE
jtcps1_20210212.rbf : sound glitches in some games

### ISSUE THREAD

**Issue by tAz-07** [jotego/jtbin#173]
Hello 

I have some sounds glitches depending on the game. 

For example very audible in "carrrier air wing" when you insert coin.

It is the same with hdmi or analog output and with original-filter option set to on or off.

My Mister is up to date.

edit : If I roll back to the previous version of the core it is ok

**Comment by ItsAtomico** [comment]
Other games with coin sound issue:

Carrier Air Wing
Forgotten Worlds
Ghouls N' Ghosts
Pnickies 
Quiz and Dragons 
U.N. Squadron

**Comment by PepAlacant** [comment]
Some sound glitches in dynasty wars. They include hanging notes when switching from one track to another in the soundtest.

**Comment by mikey1964** [comment]
i think its the same promblem as the carrrier air wing coin sound  play sf2ce go to test sound menu
play code -- OBH

**Comment by maxxsun** [comment]
knight of round  when the original filter on

**Comment by jotego** [comment]
I can hear those cracks. That wasn't there when I ran the tests. It looks like a last-minute change must have broken it. Let me have a look.

**Comment by jotego** [comment]
It's fixed now. I should really stop doing last-minute edits. The file will get uploaded in about an hour.
