### ISSUE TITLE
Latest update broke Blisster support

### ISSUE THREAD

**Issue by thehughhefner** [jotego/jtbin#174]
Hi Jotego,
Thank you for an amazing update. However, it has unfortunately broken support for Blister. For example, in Willow, the character is constantly ducking without inputting anything. Or in Final Fight, the character is constantly moving down.

**Comment by jotego** [comment]
You're right, a wrong version slipped in. I was working on the user port for an experimental feature and that version got compiled instead of the release one. Let me update the file.

**Comment by thehughhefner** [comment]
This is now
