### ISSUE TITLE
SiDi: Double Dragon & Double Dragon II: Flip Screen does not work through .ARC

### ISSUE THREAD

**Issue by mighty-mightor** [jotego/jtbin#188]
When loading DD and DD2 through .ARC file generated from the .MRA found in /mra/dd and /mra/dd2, the screen is flipped and setting the "Flip Screen" option to "On" in the OSD Switches menu has no effect.
Here are the .mra used:
Double Dragon.mra: <mratimestamp>20200318101210</mratimestamp>
Double Dragon II - The Revenge.mra: <mratimestamp>20200110232148</mratimestamp>

But if you simply rename the roms JTDD.rom and JTDD2.rom and launch the cores.rbf directly, the screen is not flipped, everything runs just fine. But of course, there is no access to any Switches.

**Comment by jotego** [comment]
I think I solved this at some point and forgot to write it here. Sorry about that.
I think it works now ok. Try deleting the config files if you still have problems.
