### ISSUE TITLE
Dynasty Wars audio glitch

### ISSUE THREAD

**Issue by Aquas77** [jotego/jtbin#189]
At the end of levels, particularly it seems when the screen goes black, it's likely this audio glitch will occur. Happens on most of the levels and at the very end of the game during the cutscenes as well.

Examples: 
https://clips.twitch.tv/SuspiciousRudeDeerChocolateRain-RFKkFXLQKsv5hT0X
https://clips.twitch.tv/TameRenownedSwanOSsloth-KA5wYLzmaVBgQcjX
https://clips.twitch.tv/AbstruseAgileLEDDAESuppy-3TOzFxGmDoMicUuW
https://clips.twitch.tv/FreezingSpoopyCougarAsianGlow-4gLs6cPS4dt8Ifvx

Still 32mb RAM, latest RBF

**Comment by jotego** [comment]
Hi Aquas,
When I changed to using the same LFO circuit as the one reverse engineered, I fixed a problem in Willow, but created a bunch of others. I think they all come down to the LFO random (noise) phase modulation.
I am tracking it here:
https://github.com/jotego/jtdd/issues/14
I will close this issue to avoid duplication. I am working on it today (fourth session on this) and I hope to close on this over the weekend.

**Comment by jotego** [comment]
I see now that the Double Dragon bug was much older. I am going to check this one separately.

**Comment by jotego** [comment]
It's hard to try anything other than the end of level 1:
-Cannot be heard at the end of level 1 with RBF 200910
-Cannot be heard at the end of level 1 with RBF 210223

**Comment by jotego** [comment]
I made an update today, which corrects a couple of minor things I found in the noise generator. It could be related to this issue. I haven't been able to reproduce the problem.

**Comment by Aquas77** [comment]
I did a full run and didn't run into the issue! Hopefully it sticks. Great work, thanks JT
