### ISSUE TITLE
[MiSTer] Cadillacs and Dinosaurs : can't map some joystick buttons

### ISSUE THREAD

**Issue by Polo2018** [jotego/jtbin#196]
Hi, 

I use an 8bitdo SN30 pro+ joystick (wireless) while playing Cadillacs and Dinosaurs with CPS 1.5 core. 
After mapping the joystick buttons (A for "attack" and B for "jump" or the reverse), using one of these buttons produces the same effect : "special attack" which is normally supposed to happen only when pressing A and B simultaneously. Therefore I can't use "attack" or "jump". 

These button mappings ("attack" and "jump") worked like a charm with previous versions of CPS 1.5 core. 

Thank you in advance and very big thanks for your incredible work. 

Best regards.

**Comment by jotego** [comment]
Hello,

Every now and then there is a question about these controllers. This isn't something I can control from the core, as it is managed by MiSTer's firmware. 
I think that removing the config files for the game normally fixes the problem. Please give it a go. 
Savvy MiSTer users will be better than me at troubleshooting this. 
I hope you can solve it easily.
