### ISSUE TITLE
sprite corruption with Windbond 32mb memory modules on tora and biocom

### ISSUE THREAD

**Issue by WolfgangBlack** [jotego/jtbin#2]
There is still sprite corruption with Windbond 32mb memory modules on tora and biocom.

**Comment by jotego** [comment]
Does it happen on Japanese version of Tiger Road too?

**Comment by Aquas77** [comment]
I am experiencing fairly heavy sprite corruption on biocom: lots of sprites looking like striped vertical lines. On 32MB sdram xs1.1 sorgelig. All versions seem to be affected. Same issue on 11/30 and 12/01 cores.

**Comment by jotego** [comment]
This is the same as #4 as Bionic Commando, Tiger Road and F1-Dream share the same sprite engine (in MiSTer and in real life arcade PCBs). So I am closing this one and sticking with just #4. I am still trying to figure this out.
