### ISSUE TITLE
CPS1 MRA alternative versions with problems

### ISSUE THREAD

**Issue by jotego** [jotego/jtbin#20]
Knights of the Round USA 911127 no sprites
Three Wonders -bootleg-.mra <= no image
Wonder 3 -Japan 910520-.mra <= doesnt work
U.S. Navy -Japan 901012-.mra 
Carrier Air Wing -USA 901130-.mra

**Comment by M-Walrus** [comment]
I dont know if this is the right place for it, but Final Fight Anniversary Edition 3-player hack has messed up graphics on the "continue" screen. you can see a little bit of glitching for all characters, but Haggar is particularly bad
![image](https://user-images.githubusercontent.com/40709481/76923259-f1dbee80-68a0-11ea-8612-f06621415542.png)

**Comment by protogem2** [comment]
https://www.romhacking.net/forum/index.php?topic=28073.msg387239#msg387239

The hack does have some known issues, inherent to the rom. Might have to wait for the rom hackers to fix this.

**Comment by houseoftheed** [comment]
The Area 88 alternate MRA files have distorted graphics after the bootup screen.

**Comment by electricsheep26354** [comment]
Japanese versions of Street Fighter II World Warrior don't allow you to configure 6 buttons, only 4. tested all Japanese rom varients all seem to work bar this controller issue. Thanks

**Comment by jotego** [comment]
All official ROMs work now in my development setup. I'll open a new issue for bootlegs and close this one.
