### ISSUE TITLE
Double Dragon II - random crashes in AttractMode

### ISSUE THREAD

**Issue by evidencedj** [jotego/jtbin#219]
Hi,

I get random crashes in the AttractMode of Double Dragon II. So after a few minutes in the AttractMode the display freezes and there are only garbled sprites. The jtsdram tests run fine. I tried it with default MiSTer Settings and my personal settings. With both settings I get these crashes from time to time.

Don't mind the LiveSplit overlay in the bottom right corner :)

![dd2crash](https://user-images.githubusercontent.com/33894818/116380428-4081e900-a814-11eb-8b36-4b86ca8ebce9.jpg)

**Comment by jotego** [comment]
Please delete the last RBF and run the updater again. The last upload I did was wrong. Sorry.
