### ISSUE TITLE
[MIST] Bubble Bobble sound problems with May 24th build

### ISSUE THREAD

**Issue by squidrpi** [jotego/jtbin#223]
Sound is broken on this latest build. Start screen fanfare will show the issue and during the game there are some strange sound effect when jumping plus other problems.

Sound is also still very low. Can the FX volume setting also be added for the music as the FX volume setting gets the sound levels back to normal?

Screen is now centered perfectly now, thanks!

**Comment by jotego** [comment]
Thanks for noticing the problem. I have corrected it. I have also increased the volume in general.
