### ISSUE TITLE
Old TV and Filters "VIDEOMODE" for VGA are missing in MiST / SiDi Cores. ( CPS1, CPS1.5, CPS2, KONAMI, bubble bobble )

### ISSUE THREAD

**Issue by PepAlacant** [jotego/jtbin#226]

**Comment by jotego** [comment]
I think they are back now. Could you please check them again?

**Comment by alessioscand** [comment]
I see them on SIDI.
BTW I'd like to point out that the "1P slow" option is the only one to have underscores instead of spaces (as if the label is not working).

Thank you so much.

**Comment by alessioscand** [comment]
Hello, may I ask here if a simpler/sharper scanlines filter is possible on SIDI? In the "dark" filter there are scanlines but the image also seems, at least to me, too "blurry" ... IMHO it would be interesting to have a filter with just scanlines, without further effects.
Thank you so much.

**Comment by jotego** [comment]
I think this is fixed now, including alessioscand's request.
