### ISSUE TITLE
s16/shinobi turns unplayable when you do a perfect in bonus stage

### ISSUE THREAD

**Issue by pacoarcade** [jotego/jtbin#227]
When you do a perfect at least in the first bonus stage it's impossible to continue playing, and the letters "P E R F E C T" don't appear. Pro tip: use fire + jump to improve shuriken throughput.

**Comment by atrac17** [comment]
I'm closing this as it's a known. Please check the core credits for known issues. It's already documented. The scrolling issue is not :)

![PXL_20210612_221130555](https://user-images.githubusercontent.com/32810066/121790108-01cca600-cbaa-11eb-8766-7f6f7d278155.jpg)
