### ISSUE TITLE
s16/shinobi scroll stuttering

### ISSUE THREAD

**Issue by ghost** [jotego/jtbin#228]
The scroll is not smooth in this game, it stutters from time to time. This is more noticeable in Mission 2. This does not happen in the S16B original game but I haven't tested Shinobi in S16A.

I use direct_video with a CRT TV.

**Comment by evidencedj** [comment]
Hi, I have tested it with my Analog IO Board 6.1 VGA Out (15kHz). Shinobi (set 6, System 16B) JTS16 v7dc5bde and can't see any stutter in scrolling. I claim the Shinobi core offers buttery smooth scrolling. Maybe it is a problem with the direct video? I played it until mission 5 and couldn't detect any stuttering.
