### ISSUE TITLE
incorrect orientation for tate mode

### ISSUE THREAD

**Issue by segacollection** [jotego/jtbin#237]
Japanese candy cab TATE orientation is -90º and thus the lovely tate-mode games are upside down in my Astro City. Unless I am missing an option to rotate them?
Edited to contain titles: Dimahoo, 19XX.
SOLVED: service menu flip.

**Comment by atrac17** [comment]
Please specify what titles/core you are referring too.

**Comment by atrac17** [comment]
Yes, these are defaulted for use with an HDMI display as default. For CRT usage, you need to turn on screen flip in the soft dips and save settings.
