### ISSUE TITLE
Dip switch settings not saving

### ISSUE THREAD

**Issue by segacollection** [jotego/jtbin#238]
CPS2 games: Dimahoo and 19XX (not tested others)

Dip switch to rotate the screen to "normal" (because it starts set to "flip"), is saved in the dip switch menu but rebooting the game resets this.

**Comment by atrac17** [comment]
You need to click save settings in the OSD after writing to EEPROM the new "soft dip" settings to create an .nvm file in media/fat/config/nvram.
