### ISSUE TITLE
(CPS1) Unable to map Coin / Start / Pause to buttons (All Street Fighter games)

### ISSUE THREAD

**Issue by HappehLemons** [jotego/jtbin#253]
Here's the arcade stick I'm using:
https://www.hitboxarcade.com/blogs/cross-up/default-profiles-and-layouts-on-cross-up

For some reason I can't bind any button Coin / Start / Pause. This happens on any Street Fighter game. 

All of my button DO work when binding to buttons B0~B5 though.

This does not happen on game like 1941: Counter Attack, where I'm able to successfully any buttons to Coin / Start / Pause to any button I want.  I also do not have this issue on other arcade cores. 

Any idea why this is happening? It makes these games unplayable as I have no way to insert a coins or start.

Unsure if this issue is related:
https://github.com/jotego/jtbin/issues/48

**Comment by Drakonas** [comment]
@jotego I don't mean to ping for no reason, but I think this should be mentioned:

![dip_content too long for MiST](https://i.imgur.com/TlfGMs2.png)

There are a bunch of warnings for the Street Fighter games saying "dip_content too long for MiST".

Not sure if this may have been the cause of @HappehLemons' issue.
