### ISSUE TITLE
MiST: jtyiear and jtsf binaries are missing

### ISSUE THREAD

**Issue by gyurco** [jotego/jtbin#259]
I've successfully built them, so I assume they're just omitted accidentally. Thanks for your work anyway!

**Comment by jotego** [comment]
JTSF should be there. I'll add it.
As for JTYIEAR, during the beta period I leave the binaries only for patrons, but it can be built indeed. The source code is already there. I'll add the binaries for JTYIEAR in a couple of weeks. I actually got a bug reported -and fixed- today, so it's indeed in beta phase.

**Comment by gyurco** [comment]
I see. Thanks!
