### ISSUE TITLE
Robocop Beta Core - Grenade Man Character Sprite

### ISSUE THREAD

**Issue by cherryuk** [jotego/jtbin#260]
The Grenade Man (Blue trousers / Grey Shirt) has his head on the last frame of animation in the opposite facing corner of the sprite when throwing the bomb. The raised leg at the end of the frame looks too short/bent?

**Comment by atrac17** [comment]
Correct, I reported it on Discord as well. Occurs in all versions.

**Comment by jotego** [comment]
![20220119_094225-screen](https://user-images.githubusercontent.com/1863036/150104973-ca6b2ec0-88a8-4cd3-abda-5380756e9478.png)

**Comment by jotego** [comment]
Fixed in commit https://github.com/jotego/jtcop/commit/7c2c4dc0e12214e3de2416599fb9636bf551fc49
I'll update the RBF for Friday.

**Comment by atrac17** [comment]
Excellent!!!
