### ISSUE TITLE
Slow music in Bad Dudes (Dragonninja)

### ISSUE THREAD

**Issue by pacoarcade** [jotego/jtbin#266]
Since some releases the background music runs slower.

**Comment by thehughhefner** [comment]
Please be specific here. Do you have a recording? How is it compared to real hardware?

**Comment by pacoarcade** [comment]
To my ears the background music sounds at different tempo in Mister version.

Sure: https://mega.nz/folder/Dw1DFYBZ#OzgQTjpYNRKRcaEM4-aAcw

**Comment by thehughhefner** [comment]
Thank you for the videos. Yes, I can hear a difference in the tempo where it is slower in MiSTer vs OG hardware. @jotego

**Comment by jotego** [comment]
I think the latest version got a wrong JTOPL (the FM sound) version by mistake. I think it's only a matter of compiling it with the right version. Sorry about the mess. I'll update it.

**Comment by jotego** [comment]
This was fixed one or two weeks ago.
