### ISSUE TITLE
Alien Syndrome - Main Character sprite blocked

### ISSUE THREAD

**Issue by Urotsukidoji** [jotego/jtbin#276]
Hi, 
  Today I've been testing Alien Syndrome and, when playing, after a while the main character sprite freezees although you can still move. Then, after several seconds, ocurrs more strange things like the fire of the weapon goes in the wrong direction.

 Cheers.

**Comment by jotego** [comment]
Hello,

I am aware of this one. I'm tracking it [here](https://github.com/jotego/jts16/issues/1). I fixed it once but it got broken again recently. I am trying to find the old version that worked so I can find out what went wrong.

I'll close this issue as I am tracking it in the core repository.

Thanks for reporting it.
