### ISSUE TITLE
Strider bugfix patch.

### ISSUE THREAD

**Issue by toaks2804** [jotego/jtbin#280]
Is there a way to get a MRA for the new Strider bug fix patch that is available on romhacking.net? It fixes a few music tracks that don't play and restores a bit of artwork. Thanks!

**Comment by MJY71** [comment]
https://www.romhacking.net/hacks/6758/

**Comment by jotego** [comment]
I'll release the MRA today

**Comment by jotego** [comment]
Fixed in 1bee3db
