### ISSUE TITLE
Newer MRA JTS16B & JTS16

### ISSUE THREAD

**Issue by kaloun34** [jotego/jtbin#281]
Some newer MRAs don't seem to work !

Ex: 
- "Lock On" requires debugs.zip file
- "Ace Attacker"  black screen
- "Atomic Point"  black screen
- "ISG Selection Master" black screen
- "Snapper" black screen 
- "Quartet" black screen

**Comment by jotego** [comment]
A bunch of games that are not currently supported by the core got pushed by mistake in the latest update. I have removed them for now.
