### ISSUE TITLE
System16  Excite League: Unresponsive controls

### ISSUE THREAD

**Issue by Spacejockey-GH** [jotego/jtbin#282]
Impossible to choose something at will. In "service mode" > "input Test" only the start and coin buttons are detected as pressed. They have always malfunctioned since the beta phase of the core.

Maybe if you are not implementing the board that handles the trackball this can cause this problem. 
Here I leave you the **gerber** of the S16/S18 plate, ref. 834-6180 made by Apocalypse on the arcade-projects forum
[gerbers_837-7968.zip](https://github.com/jotego/jtbin/files/8547585/gerbers_837-7968.zip)

For reference:
https://www.arcade-projects.com/threads/found-sega-trackball-i-o-board-ref-834-6180-or-837-8685.16103/

P.D: the original link where this topic was discussed is dead.

**Comment by jotego** [comment]
This game is not currently supported and you can see why. I am sorry it got in JTBIN by mistake.
