### ISSUE TITLE
Rastan - music seems too fast in jtrastan_20220429.rbf

### ISSUE THREAD

**Issue by TheSouthy** [jotego/jtbin#288]
Hi Jotego - I have noticed that the music seems to be playing a bit too fast in the latest Rastan core, jtrastan_20220429.rbf. I have reinstalled the earlier rbf (2022_04_08) and it is definitely slightly slower in that version - watching this video of Rastan being played makes me think that the slower music may be more accurate https://www.youtube.com/watch?v=RfdOIMkXotw

Thanks for all the work on these cores.

**Comment by jotego** [comment]
Fixed in 3e24d5d
