### ISSUE TITLE
Block Block  - Pad doesn't move left-right

### ISSUE THREAD

**Issue by Urotsukidoji** [jotego/jtbin#291]
Hi, 
   I've been testing Block Block core and, although I defined keys for directions, when I start a game, the pad doesn't move in any direction (left or right). The rest of buttons (Start, Pause, etc...) seem to work fine.
 
  Cheers.

P.D.  Someone has told me that this game is controlled with a Spinner (sorry, didn't know that detail).
 JoTeGo, you can close this issue.

 Sorry for the inconvenience.

**Comment by jotego** [comment]
The version whose MRA title says joystick can be controlled with a joystick. The other versions are controlled with a mouse. If you show the pause screen, this information is also written there.
