### ISSUE TITLE
MiSTer popeye rbf is actually the one for MiST

### ISSUE THREAD

**Issue by WolfgangBlack** [jotego/jtbin#3]
MiSTer popeye rbf is actually the one for MiST
Totally crashes MiSTer and has the same CRC as the MiST one....

**Comment by eubrunosilva** [comment]
try this one: https://github.com/jotego/jtbin/tree/master/mister/popeye/releases

**Comment by jotego** [comment]
Sorry about the mistake, @WolfgangBlack. I have been editing the scripts today to try to avoid this from happening again.

**Comment by WolfgangBlack** [comment]
Oh, no apologies needed.
I noticed it and wanted to inform you of that!
Thanks for the cores!
Easy mistake to make when you are managing multiple platforms for the same
cores.
