### ISSUE TITLE
CPS1: Street Fighter II' Turbo  Hyper Fighting -Japan 921209-.mra Missing Button Mapping

### ISSUE THREAD

**Issue by misteraddons** [jotego/jtbin#30]
Turbo Hyper Fighting is missing mapping for B3, B4, and B5.

I copied the button names section from Street Fighter II'  Hyper Fighting -USA 921209-.mra 

`` <buttons names="B0,B1,B2,B3,B4,B5,Start,Coin,Pause" 
        default="A,B,X,Y,R,L,Select,Select,Start"/>
``

And can now map B3, B4, and B5 but they do not trigger in game.

**Comment by jotego** [comment]
Fixed.
