### ISSUE TITLE
Screen gets black (Combat School Core)

### ISSUE THREAD

**Issue by Urotsukidoji** [jotego/jtbin#311]
Hi there,
    Some people, included me, have found that recently this core (Combat School) shows a black screen and the game do not boot.

 Greeting (saludos :D).

**Comment by jotego** [comment]
Thank you. I am tracking this [here](https://github.com/jotego/jtcontra/issues/16).
I have deleted the bad versions from JTBIN (3994778). The latest working version is jtcomsc_20220819.
