### ISSUE TITLE
Several MRAs missing

### ISSUE THREAD

**Issue by Shaneus2k2** [jotego/jtbin#318]
Noticed this after running an update_all, the following ROM files were deleted from games/mame without being re-downloaded:

mbombrd.zip / Muscle Bomber Duo
slammast.zip / Saturday Night Slam Masters
pang3.zip / Pang! 3
dino.zip / Cadillacs and Dinosaurs
punisher.zip / The Punisher
wof.zip / Warriors of Fate

Verified, and noticed that their associated MRAs no longer exist, either locally on my MiSTer or this repository.

Apologies if this is somehow a mistake on my end!

Update: Noticed that all excl. Pang! 3 are CPS1.5 titles. Hope that helps!

**Comment by jotego** [comment]
Fixed in b4680ffd2

**Comment by foxp4v** [comment]
Hello, Pang 3 mra and roms still not being downloaded

**Comment by jotego** [comment]
Yes, this is being tracked in a separate issue.
