### ISSUE TITLE
wofch proper a/b/c board configs for GFX

### ISSUE THREAD

**Issue by atrac17** [jotego/jtbin#319]
This config should be added as a flag to mame2mra to fix setname `wofch` for CPS Changer / CPS Dash hardware.

Reference this [commit](https://github.com/jotego/jtbin/commit/fbfd533015928357401027e7e3388ce308fe5ffb) for further information. It's missing the B-Board and C-Board config information required.

You generate the following which results in improper GFX:

        <part>
            00 04 80 04 80 0C 80 1C
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
            FF FF FF FF FF FF FF FF
        </part>
        
Replace with this and wofch GFX are proper:

        <part>
            00 04 80 04 80 0c 80 1c 
            ff ff ff ff ff ff ff ff 
            32 ff 00 02 04 06 26 28 
            2a 2c 2e 36 30 30 02 04 
            08 30 25 40 88 73 ff 20 
            ff ff ff ff ff ff ff ff 
            01 23 45 67 54 16 30 72 
            51 51 51 ff ff ff ff ff
        </part>

**Comment by jotego** [comment]
Excellent! Thanks. I've added it in 768f8265. JTBIN is updated too.
