### ISSUE TITLE
Duplicate MRAs and folders

### ISSUE THREAD

**Issue by lsnderick** [jotego/jtbin#320]
There are some duplicates in the main folder and _alternatives.

Main:
Gun Smoke.mra
Gun.Smoke (World, 1985-11-15).mra

Night Warriors Darkstalkers Revenge (Euro 950316).mra
Night Warriors Darkstalkers' Revenge (Euro 950316).mra

Ring of Destruction Slam Masters II (Euro 940902).mra
Ring of Destruction Slammasters II (Euro 940902).mra

Street Fighter Alpha Warriors Dreams (Euro 950727).mra
Street Fighter Alpha Warriors' Dreams (Euro 950727).mra

_alternatives:
_Night Warriors Darkstalkers' Revenge inside the folder - every *.mra is doubled with and without ' symbol

Duplicate folders:
_Ring of Destruction Slam Masters II
_Ring of Destruction Slammasters II

_Street Fighter II'  Champion Edition (Extra space)
_Street Fighter II' Champion Edition

**Comment by jotego** [comment]
Thank you for the detailed report. It has made things much easier. The changes should be available on bd4db79
