### ISSUE TITLE
Black screen on jtContra core with Analogue pocket 

### ISSUE THREAD

**Issue by manichispanic999** [jotego/jtbin#329]
The newest update from April 14th now has the contra core showing a black screen when any rom is selected.

**Comment by jotego** [comment]
Sorry about that, you need to regenerate the ROM files from the latest MRA files

**Comment by manichispanic999** [comment]
> Sorry about that, you need to regenerate the ROM files from the latest MRA files

I'm still having the black screen problem, as well as with the combat school core. I think it may be a problem with the panella updater, i'll wait for an update from them.

**Comment by jotego** [comment]
I'm sorry to hear that. I've tested the updated files and they work. Let me know how it goes.
