### ISSUE TITLE
Street Fighter Zero 2 Alpha (Japan 960805)

### ISSUE THREAD

**Issue by h1deous** [jotego/jtbin#332]
As per: https://github.com/jotego/jtcores_mister/issues/9

When you finish a game and enter your name, you’re greeted with the « score ranking screen ». Icons are surrounded by 2 blocks in solid blue color (cf. attached screenshot).
![233058451-910fd9ba-71b9-4169-98ed-7bae0df1c794](https://user-images.githubusercontent.com/51401944/235124145-19c34aad-53f7-484d-8988-4808acdc603e.jpeg)

**Comment by jotego** [comment]
I think this have reported before and closed because users found it on real hardware too. The last time it was reported and closed was maybe last week in https://github.com/jotego/jtcores/issues

**Comment by h1deous** [comment]
No, it was closed because theypsilon wanted it reported here. It doesn't happen in real hardware. 
See: https://www.youtube.com/watch?v=lDsV1gUsBLo&t=882s

**Comment by gdlrauro** [comment]
> I think this has been reported before and closed because users found it on real hardware too. The last time it was reported and closed was maybe last week in https://github.com/jotego/jtcores/issues

Hi, have the CPS2 board of this Game and the blue boxes doesn't exists. If you want i can send you an image direct front my monitor to prove that.
Regards.
