### ISSUE TITLE
All versions of TNZS are filed in Alternatives on Pocket

### ISSUE THREAD

**Issue by espiox** [jotego/jtbin#336]
The Pocket zip for jtkiwi has every version of The NewZealand Story filed in the "_alternatives" folder, so updaters will skip by default. "The NewZealand Story (World, old version) (P0-041A PCB).json" should be moved back into Assets\jtkiwi\jotego.jtkiwi

**Comment by jotego** [comment]
Duplicated in #351 
Let me handle this issue in #351, together with the other ones
