### ISSUE TITLE
Sound problem in Midnight Resistance on MiST

### ISSUE THREAD

**Issue by gkralicek26** [jotego/jtbin#338]
Seems the sound is weird (FM i guess) in some area of the game. This is particularily obvious during the first few seconds of the first stage where you can clearly hear some "pshhh" while the music is playing which are not part of the soundtrack (i can compare as i got the original PCB)

**Comment by jotego** [comment]
Thanks for reporting it. This is a known problem pending attention at the moment. It's tracked [here](https://github.com/jotego/jtcores/issues/198).
