### ISSUE TITLE
Double Dragon screen cutoff in Pocket

### ISSUE THREAD

**Issue by HatchiFr** [jotego/jtbin#342]
Hello,
It seem that the screen cutoff is not realy fixed.

I'm using the last version of the core + manually created rom.
Did I missed something ?

EDIT :
There is the link of the picture : [Pic 1](https://imgur.io/sKbFonl?r)

Take Care.

**Comment by jotego** [comment]
It looks like the Pocket firmware doesn't like the 232 height. I have adjusted the core to produce 240 pixels height. That works well with the Pocket.
I will publish the files next Friday
