### ISSUE TITLE
CPS2 Progear Rapid Shot Non-functional

### ISSUE THREAD

**Issue by jasoncarlough** [jotego/jtbin#346]
There is a button assignment for Rapid Shot in the Controls menu but it is completely non-functional in game.

**Comment by jotego** [comment]
Enter the setup mode (F2 on MiSTer or right button+start button) and navigate until you get to this screen. Then enable it.

![20231102_080718](https://github.com/jotego/jtbin/assets/1863036/5d5b664b-767e-4a8d-b7a5-8709bf54ad28)

**Comment by jasoncarlough** [comment]
I can’t seem to get into setup mode. Does it work on Analogue Pocket?

**Comment by jotego** [comment]
![pocket](https://github.com/jotego/jtbin/assets/1863036/f4457d59-c305-4f1f-a33c-a6660607be23)

**Comment by jasoncarlough** [comment]
Ooohhh… sorry about that. I was holding right on the d-pad. Thank you so much for your help and patience.
