### ISSUE TITLE
Pocket : key mapping for player 2 when docked (CPS1 or 2)

### ISSUE THREAD

**Issue by mpatour** [jotego/jtbin#348]
Hello! Great work you've accomplished so far.
Is there a way to remap keys for player 2 when using the dock?
Thanks

**Comment by jtmiki** [comment]
Hello!
Key mapping is an Analogue firmware feature. 
There is nothing we can do in the core about it. We have requested Analogue to support this feature. 
Hopefully they will include it in future releases. 
Thank you.
