### ISSUE TITLE
Street Fighter 2 Hyper Fighting Demo/Transition Screens

### ISSUE THREAD

**Issue by RetroDriven** [jotego/jtbin#35]
The Demo music cuts off right before the character select screen. It also seems to cut off after the Demo is done and looping through again. There seems to be some noticable artifacts when switching from different loading/transition screens. It's like it pauses briefly and cuts to the next transition.

**Comment by RetroDriven** [comment]
The Demo music seems to be fine with Champion Edition and World Warrior but I do see the same delay in the transitions between screens there as well.

**Comment by jotego** [comment]
Could you specify the exact MRA file where you saw this?

**Comment by RetroDriven** [comment]
Street Fighter II'  Hyper Fighting -World 921209-.mra

This is the only MRA I can get working. The World MRA versions for all the SF2 games are the only ones working for me for some reason.

**Comment by RetroDriven** [comment]
I can record a quick video with audio from the real PCB if you'd like. My PCB is the USA 921209.

**Comment by RetroDriven** [comment]
Maybe this is what really happens for the World version and I'm just used to the USA version though.

Is the USA version working for you on your end?

**Comment by RetroDriven** [comment]
https://youtu.be/qOmkjK56ccc

That's what I'm used to seeing so maybe it's just World vs USA and the cut off doesn't happen with USA and the Don't User Drugs screen.

**Comment by RetroDriven** [comment]
After testing my PCB and the ROMs within MAME the music cut off is actually normal for the World version. Very interesting.

The black levels still seem more noticeable during the transition screens I think. I never noticed the graphics like Flags flashing like that until now. Another interesting thing you don't think about it notice until something like this happens in Mister. Pretty cool stuff in my opinion.
