### ISSUE TITLE
Pocket: Different versions of games use the same rom filename.

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtbin#352]
In the Outrun core "Out Run (deluxe sitdown) (Enhanced Edition v1.0.3)" and "Out Run (sitdown-upright, Rev B) (Enhanced Edition v1.1.0)" both create and use roms called "outrueha.rom"
In CPS2, "X-Men Children of the Atom (Asia 941219)" and "X-Men Children of the Atom (Euro 950105)" both create and use roms called "xmcotar1.rom"

**Comment by jotego** [comment]
This comes from a limitation in the MiST firmware, which is the system that was using these .rom files before the Pocket. I'd rather not change this for the Pocket alone. Let me see if the MiST firmware maintainers are interested in supporting longer file names.

- [ ] https://github.com/mist-devel/mist-firmware/issues/109
- [ ] update jtframe to support the untrimmed names

**Comment by jotego** [comment]
The changes are done, but I won't update the files in JTBIN straight away as this will break the setup of current Pocket users and force regenerating all .rom files -not just the ones you mentioned-

**Comment by mattpannella** [comment]
i should have our archive rom set updated with the new file names tonight or tomorrow. i will post here again when its done to confirm, but you can probably plan to release this update whenever you want :) @jotego

**Comment by mattpannella** [comment]
ok that went much quicker than i thought haha. you're good to go!

**Comment by jotego** [comment]
Completed in yesterday's update
