### ISSUE TITLE
Pocket - November 17 update missing files

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtbin#358]
None of the pocket cores include the rbf_r files except for System 16. For System 16 only the rbf_r file is included, nothing in Assets, Presets, or Platforms.

**Comment by jotego** [comment]
I was just adding them as you were writting the issue!
It's ready now.
https://github.com/jotego/jtbin/commit/045982fd445b54fd4193a0b7a2b5cff3e73aa08e
