### ISSUE TITLE
Jtkicker mra problem

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtbin#361]
There seems to be a problem with Shao-lin's Road (set 2), on MiSTer, the sprites are corrupt. And while trying to create the rom for the pocket it gives an error:
interleaved part size mismatch. (16384 vs. 8192) 

The resulting rom file doesn't match the MD5 given in md5.md

**Comment by jotego** [comment]
There was a problem in the sprite data location in the MRA file. But even after fixing it, the sprites were corrupted -though in a different way. I am retiring this set for now (7023e12)
