### ISSUE TITLE
Pocket: Black Areas on Bubble Bobble and Tokio

### ISSUE THREAD

**Issue by GoldZabu** [jotego/jtbin#366]
On the newest version of the Bubble Bobble pocket core, Bubble Bobble has a black area in the lower right that doesn't seem to obscure the sprites, and Tokio has a black strip up the left side of the playable area that the sprite can fly over. Also, on the Bubble Bobble title screen, part of the logo seems to appear in the bottom left of the screen.
![20231208_222834](https://github.com/jotego/jtbin/assets/126714968/c6f95b0d-2bd1-47f0-9f41-7c8947a36137)
![20231208_222852](https://github.com/jotego/jtbin/assets/126714968/0da6bed4-3f20-49ec-a573-d03f5ada84fe)
![20231208_222920](https://github.com/jotego/jtbin/assets/126714968/1a277c20-a267-4024-ad7e-7e784a0163d6)

**Comment by jotego** [comment]
Duplicated in https://github.com/jotego/jtcores/issues/455

Thanks for taking the time to report it. For filing core issues, use the jtcores repository if possible. 

Thanks again
