### ISSUE TITLE
Bubble Bobble core for Analogue Pocket

### ISSUE THREAD

**Issue by mpatour** [jotego/jtbin#375]
Hi
Great work so far. Here is some other graphical issues I would like to report :

First one : when dragons are arriving inside a bobble at the beginning of a level
second one : on the progress screen at the end of a game

ps : I'm also unable to play the game : no input is working, I certainly don't have the proper beta.bin file (can't find later version than the one of 5th of January).
As a result, all pictures were taken during the demo.
![IMG_20240129_210208~2](https://github.com/jotego/jtbin/assets/142811869/503b90f8-7e95-477b-831c-46a7972ea54e)
![IMG_20240129_210336~2](https://github.com/jotego/jtbin/assets/142811869/22bf4738-39e8-4f1f-9988-f4ed3303adce)
![IMG_20240129_210723~2](https://github.com/jotego/jtbin/assets/142811869/fd90789e-975b-48a7-bf43-bc56833b06e2)

**Comment by jotego** [comment]
I cannot reproduce this at all. You most likely have an old or corrupted version of the core files. The fact that it does not work with the latest beta.bin, from the 5th of Jan, is a hint too that the installation is broken somewhere.

Try installing on a fresh SD card. All beta cores should work with the 5th of Jan beta.bin file and there should be no GFX issues, at least so blatantly obvious ones, in Bubble Bobble.
