### ISSUE TITLE
CPS1/CPS1.5 Sangokushi II asia Chinese bootleg MRA

### ISSUE THREAD

**Issue by mhmetalheart** [jotego/jtbin#379]
I have a request, can you create a mra for: wofabl - Sangokushi II bootleg (wof Asia Chinese bootleg). On CPS1.5/CPS1. 
I remember you wrote Sangokushi II huo feng huang Asia Chinese bootleg (wofhfh) ago, it works great. Use CPS1 core. But you deleted.

**Comment by jotego** [comment]
Many bootlegs don't work in the core as they have different hardware. If it is not there already, that's probably the reason.
