### ISSUE TITLE
pocket: warrior of fate rom no sound when using the mra.exe to convert zip to rom

### ISSUE THREAD

**Issue by ZXTFINAL** [jotego/jtbin#380]
pocket: warrior of fate rom no sound when using the mra.exe to convert zip to rom
I forgot the qsound.zip during my first try. It failed. the second try worked but no sound
![图片](https://github.com/jotego/jtbin/assets/53009474/49720008-82a5-498d-908a-078658f16bcb)

**Comment by jotego** [comment]
You probably have a bad version of the qsound.zip file.

**Comment by ZXTFINAL** [comment]
> You probably have a bad version of the qsound.zip file.

OK, I will try others
