### ISSUE TITLE
Double Dragon MiSTer

### ISSUE THREAD

**Issue by deadlygroove** [jotego/jtbin#386]
Hey Jotego,
I appreciate all the work you do and happy to be a patreon member of your work. I wanted to let you know that Double Dragon locks up when getting to the end of Mission 2 and I am not able to progress any further. It also locks up during letting the demo play. This happens on all versions. I've tried everything I could think to do on my end but I am getting the same freezing issue. I know you're busy but I just wanted to let you know of this issue with the core.
Hope your weekend is well with you and your team,
Gary

**Comment by jotego** [comment]
Hello Gary,

I think you might talked about this on Discord a few weeks ago. We tested it back then and could not reproduce the issue. I have tested it again on the latest version and I can play normally all the way to mission 3. The demo runs ok too.

Try deleting your _Arcade folder and running update all again, you may be playing to a very old version (?). Also delete old config files related to Double Dragon games.
