### ISSUE TITLE
Sly Spy for Analogue Pocket has been deleted.

### ISSUE THREAD

**Issue by joshcampbell191** [jotego/jtbin#387]
It would appear that Sly Spy for the Analogue Pocket was removed in the last release. I don't know if this was intended or not.

https://github.com/jotego/jtbin/commit/34d904f1c12f043f067b7a74c78d9f597b037cc7#diff-fda3bd37983ff4bbe38755aba84e3f2f7c2b3252349838de4b6e74f64b9650de

Can you please confirm?

**Comment by jotego** [comment]
Thank you for noticing. I have updated the files. It was not intentional. Apologies.
