### ISSUE TITLE
request: pass license key info to updaters, for analogue pocket releases

### ISSUE THREAD

**Issue by mattpannella** [jotego/jtbin#397]
right now we have special conditions hardcoded to look for JTBETA as a check for whether a core requires the license or not
would it be possible to include that info in a file that the updaters can read from? 
we have another developer adding beta key checks for their cores, and instead of adding a 2nd custom check, we would like to have a standard format devs can supply to let updaters know a beta file is required, to avoid having to add custom code every time

if you just include this file (and fill in whatever the key file is, from data.json) with the core, then we can check for it and everything else will work as it does now:
`Cores/{corename}/updaters.json`
```json
{
  "license": {
    "filename": "beta.bin"
  }
}
```

this would also give you the freedom to change the beta key file name without letting us know, or requiring any changes

**Comment by jotego** [comment]
Thank you for this suggestion. I have implemented it and it will be visible in JTBIN from the next update -hopefully today.
