### ISSUE TITLE
request: include the default display modes in video.json for all jt pocket cores

### ISSUE THREAD

**Issue by mattpannella** [jotego/jtbin#399]
the updaters currently have an option to force the displays into each core, but we could remove that if the cores just define their list 
here is all the generic display modes that are not platform specific:

```json
"display_modes": [
      {
        "id": "0x10"
      },
      {
         "id": "0x20"
      },
      {
         "id": "0x30"
      },
      {
         "id": "0x40"
      },
      {
         "id": "0xE0"
      },
      {
         "id": "0xE1"
      }
    ]
```

**Comment by jotego** [comment]
Very good suggestion. Let me take it to this other [issue](https://github.com/jotego/jtcores/issues/804) that was opened about the same time as yours.
