### ISSUE TITLE
CPS1 left pixel

### ISSUE THREAD

**Issue by jotego** [jotego/jtbin#40]
Leftmost pixel may be one line lower than it should. Check out SFZ

**Comment by paulb-nl** [comment]
This can be seen easily on the intro of SF2. It seems like sprites are not affected?

![20200410_171803-screen_pixel_shift](https://user-images.githubusercontent.com/2227984/79038176-9bc84580-7bd7-11ea-869f-0866c5cf633a.png)

**Comment by jotego** [comment]
Fixed. Will release next Friday.
