### ISSUE TITLE
Super Puzzle Fighter II X graphics glitch?

### ISSUE THREAD

**Issue by xenyou** [jotego/jtbin#400]
I'm not sure if this is a bug or original behavior.
But I'll report it.

There is a gabage frame in Super Puzzle Fighter II X.
I'm using Super Puzzle Fighter II X (Japan 960531).mra

You can see the frame from 0:03
https://www.youtube.com/watch?v=puPs9vq7Syk

![Screenshot 2024-09-27 at 19 55 08](https://github.com/user-attachments/assets/2b715cb2-9df5-41c2-87a3-e5d34fcfa3de)

**Comment by jotego** [comment]
This question came up a long time ago when I first made the core. If I remember correctly, the veredict back then was that it was the correct behaviour.

Thanks for reporting it.
