### ISSUE TITLE
SF2 USA MRA Versions

### ISSUE THREAD

**Issue by RetroDriven** [jotego/jtbin#43]
This might just be me but does anyone else have issues running the SF2 USA MRA files? WW, CE, and HF all won't load for me. It will just stay at a black screen and you can hear the plane sound you'd hear when you travel to the different countries/players.

**Comment by jotego** [comment]
Most of them -but not all- actually work. Try this one.

[Street Fighter II  The World Warrior -USA 910214-.mra.zip](https://github.com/jotego/jtbin/files/4464759/Street.Fighter.II.The.World.Warrior.-USA.910214-.mra.zip)

**Comment by jotego** [comment]
I'm closing it here as I'm tracking it in #20. I'll be updating the list later today.

**Comment by RetroDriven** [comment]
This one works! It seems to be an issue with the Merged ROMs I'm using maybe?

**Comment by RetroDriven** [comment]
Is this MRA different vs the one you have on your Google Drive for the beta?

**Comment by jotego** [comment]
Yes, I'm working on the MRA files that failed. I will update the Google Drive files next Friday.
