### ISSUE TITLE
SF2 intro audience sprite issue

### ISSUE THREAD

**Issue by paulb-nl** [jotego/jtbin#45]
During the punch, parts of the body of the guy in the audience on the far right disappear.

![SF2_missing_sprite1](https://user-images.githubusercontent.com/2227984/79066389-d99c9b00-7cb7-11ea-9fd4-35ed4d3c81c5.jpg)
![SF2_missing_sprite2](https://user-images.githubusercontent.com/2227984/79066390-db665e80-7cb7-11ea-99de-ec6064926b9b.jpg)

**Comment by jotego** [comment]
Could you confirm the version please?

**Comment by paulb-nl** [comment]
jtcps1_20200410

Street Fighter II'  Champion Edition -World 920513-
Street Fighter II'  Hyper Fighting -World 921209-
Street Fighter II  The World Warrior -World 910522-

You can also see it in Smokemonsters video with all 3 games:
https://youtu.be/uTGqC1k9qYE?t=630

**Comment by Chocobobobo** [comment]
At least, his hat is still around...

**Comment by jotego** [comment]
I've seen it happening now. I'll get to it. Thank you :-)

**Comment by jotego** [comment]
Fixed
