### ISSUE TITLE
CPS1 Missing graphics in Quiz _ Dragons  Capcom Quiz Game -Japan Resale Ver. 940921-.mra

### ISSUE THREAD

**Issue by Chocobobobo** [jotego/jtbin#47]
There should be a board, now the character is floating in the air.
There should also be an overlay when you are in a fight.
Correct (From US version)
![20200413_192843-screen](https://user-images.githubusercontent.com/23947970/79153611-6c2f5e00-7dce-11ea-8ecd-cd1ccf91cbbf.png)
![20200413_192852-screen](https://user-images.githubusercontent.com/23947970/79153612-6cc7f480-7dce-11ea-8f83-26211b31d2cd.png)

Currently in JP version 
![20200413_191844-screen](https://user-images.githubusercontent.com/23947970/79153678-85380f00-7dce-11ea-9ec5-6488008c36b9.png)
![20200413_191851-screen](https://user-images.githubusercontent.com/23947970/79153681-85d0a580-7dce-11ea-9819-b7b2d508c0ab.png)

Good luck and keep up the great work!

**Comment by jotego** [comment]
Maybe you had disable that layer with the keyboard inadvertedly? You can disable graphic layers using keys F7 to F10.
I have tested here and it worked ok. I can create the effect of your images if I press F8 and disable the SCR2 layer.
