### ISSUE TITLE
CPS 1 - Games - wrong number of button

### ISSUE THREAD

**Issue by wwark** [jotego/jtbin#49]
Hello,

In the mra's of **Commando** there are 4 buttons (B0 to B3) but in the test mode there is just two buttons for this game.
In the mra of **Dinosaur hunter** there are 4 buttons (B0 to B3) but in the test mode there is just two buttons for this game.
In the mra's of **Final Figh**t there are 3 buttons (B0 to B2) but in the test mode there is just two buttons for this game.
In the mra's of **knight of the rounds** there are 4 buttons (B0 to B3) but in the test mode there is just two buttons for this game.
In the mra's of **Pnickies** there are 3 buttons (B0 to B2) but in the test mode there is just two buttons for this game.
In the mra's of **Mercs** there are 4 buttons (B0 to B3) but in the test mode there is just two buttons for this game.
In the mra's of **The king of Dragons** there are 4 buttons (B0 to B3) but in the test mode there is just two buttons for this game.
In the mra's of **Three Wonders** there are 3 buttons (B0 to B2) but in the test mode there is just two buttons for this game.

Thanks,

**Comment by jotego** [comment]
You're right about the test mode but I don't know what to do. Often arcade games do have input connections to the CPU that aren't apparently used. For Final Fight the extra button is marked as _cheat_. Maybe if I delete the buttons someone will come up saying that now they cannot perform some obscure hack.

Let me leave this open for a while and see if we can gather more opinions.

**Comment by wwark** [comment]
ok don't know there is some extrat cheat button.
so it is based to mame regarding the number of buttons. The cheats is extra feature maybe not present on real arcade cabinet.

**Comment by wwark** [comment]
I think maybe change the name of the button to label it for his purpose like BC1 (button cheat 1)

**Comment by jotego** [comment]
I will publish the files following MAME database and let MRA editors modify them. Incorporating exceptions to all these cases in the MRA generation program is too much an overhead for me. I am counting on MRA editors to create many MRA variations, such as localised, with cheats on them, hacks, etc. So this can be another area for editors.
