### ISSUE TITLE
How to build Popeye (Japan).mra ? 

### ISSUE THREAD

**Issue by wwark** [jotego/jtbin#5]
Hi,
The rom Popeye (Japan) is quite different.
How can we do the mra file for this rom ?
Thanks !

**Comment by jotego** [comment]
Hi,
Sorry for the delay in response. I didn't reply when the e-mail came in and after that I lost track of it. Apologies.
The MRA files for this are available from the Bruno Silva set. I usually upload them here too but I am not the maintainer of the MRA files. If you need to build an MRA file you can use the MAME driver source file and compare the rom files there with the ROM order in the file Makefile in the rom folder of the source core repository [here](https://github.com/jotego/jtpopeye/tree/master/rom).
