### ISSUE TITLE
CPS1: Some games freezing on loading in new MiSTer20200419

### ISSUE THREAD

**Issue by Left-Empty** [jotego/jtbin#51]
Some games are freezing when the rom is loading. The green diode never turns on and they are just stuck, with no way to intereact with the MiSTer
I experienced it with my darling The King of Dragons, and tested it with Captain Commando and the bootlegs of CPS 1.5 games.

Best regards

**Comment by jotego** [comment]
Hi, this is a MiSTer firmware bug. We have compiled a fixed version in discord. We have to wait for Sorgelig to fix the release file.
