### ISSUE TITLE
Missing countdown layer in Captain commando

### ISSUE THREAD

**Issue by jorgalancomin** [jotego/jtbin#53]
Hi:
When you finish your gameplay in Captain Commando , and you can continue , the countdown number is missing, you heard the sound of the numbers going down, a giant star is display , but one layer is missing.

Thx.
Jorge Galán.

**Comment by jotego** [comment]
It is realy a strange problem because when I checked it there was no such text in any layer so it wasn't a layer priority problem. I'll come bak to it.

**Comment by jotego** [comment]
Text is written in the upper half of SCR1 layer but the core somehow shows the bottom half instead.

**Comment by jotego** [comment]
Fixed in https://github.com/jotego/jtcps1/commit/365911c30af8f2f2b13ba0f4effaf7b3ca692443
