### ISSUE TITLE
gun.smoke screen rotation problem

### ISSUE THREAD

**Issue by Gerome91** [jotego/jtbin#54]
Hello,
I have a problem with Gunsmoke. It is impossible to rotate the screen on CRT in RGB. All 1942 shooting games, bionic commando, Mercs ect ... impossible to rotate the screen on CRT. Thank you

**Comment by jotego** [comment]
Hi Gerome,
I'm sorry but rotation on CRT is not supported. It has severe technical implications. The option on the OSD appears as it has meaning for HDMI output but it's not applicable to CRT screens.
Sorry
