### ISSUE TITLE
Double Dragon II - missing/garbled/blank screen output on core startup

### ISSUE THREAD

**Issue by mholzinger** [jotego/jtbin#55]
MiSTer ver: 191019
OS: Buildroot 2017.02
MRA: Double Dragon II - The Revenge.mra (md5 b5586d0f1201c17162a4aa831cc2bc7d)
Core: jtdd2_20200331.rbf (md5 d633568faa6aa31f2d1037e9c1bb1880)

Issue:
Core displays missing or garbled text on startup.

![20200426_213550-screen](https://user-images.githubusercontent.com/235958/80320635-7a1cb000-87cc-11ea-9106-a187579fcdca.png)

Workaround: 

1 - Display credits to enable sprite output

![20200426_213604-screen](https://user-images.githubusercontent.com/235958/80320646-8ef94380-87cc-11ea-9134-7e1773b0934e.png)

2 - Call in game reset from menu (F13)

![20200426_213631-screen](https://user-images.githubusercontent.com/235958/80320672-a9cbb800-87cc-11ea-8894-fb1d24a8e5e9.png)

3 - Display issues persist but are now visible

![20200426_213659-screen](https://user-images.githubusercontent.com/235958/80320684-b6501080-87cc-11ea-886f-f54f13e2abd8.png)

**Comment by jotego** [comment]
Try resetting with F3 key after loading. It is a problem with the MCU very hard to track. Or maybe a problem with my glue logic and the reset. I have it in the back of my mind. For now just use F3.

**Comment by jotego** [comment]
Summary of the situation here: https://github.com/jotego/jtdd/issues/8
