### ISSUE TITLE
cps1 Willow bug with 1/5/20 core

### ISSUE THREAD

**Issue by mdd45** [jotego/jtbin#57]
I have a bug to report with 1/5/2020 cps1 beta core with Willow:

![JPEG_20200501_163934](https://user-images.githubusercontent.com/31571067/80811202-14fefb00-8bce-11ea-88f8-6a8eba427a03.jpg)

Also there are gfx glitches with the bootlegs of Cadillacs and Dinosaurs and Punisher.

**Comment by rarcos** [comment]
Cadillacs & Dinosaurs bootleg got fixed using this mapper in the MRA:

`<part> 25 40 88 73 FF </part>`

**Comment by mdd45** [comment]
with this mapper i get a black screen, so still no for me.

**Comment by jotego** [comment]
I'm uploading a file as soon as the compilation finishes. This has been caused by a corrupted file during compilation.

**Comment by jotego** [comment]
The RBF file in the original attachment should work now correctly.

**Comment by mdd45** [comment]
thanks, now works!
