### ISSUE TITLE
mister: update_jtcores.sh doesn't follow new _Arcade/core folders schema?

### ISSUE THREAD

**Issue by piso77** [jotego/jtbin#6]
update_jtcores.sh script still download rbf files in _Arcade instead of _Arcade/core - perhaps that should be updated to reflect the new schema?

**Comment by eubrunosilva** [comment]
Hi
if you use an ini you can change the folder.
but the new script will be adapted soon to download these cores.

**Comment by jotego** [comment]
Fixed
