### ISSUE TITLE
CPS1 Distorsion at the bottom of the screen in SF2 WW

### ISSUE THREAD

**Issue by Chocobobobo** [jotego/jtbin#60]
Checked on latest CPS1 core (0502) by my good friend Terminator2K.  April 10th and 17th core version are OK.
![MiSTer_FPGA_-_Street_Fighter_II_-_The_world_Warrior_Screenshot_2020-05-04_22-29-43](https://user-images.githubusercontent.com/23947970/81023048-83aeb380-8e6f-11ea-84ca-b943c9ee47d1.png)

**Comment by jotego** [comment]
That's likely to be a fault in the new DMA module. I'll check it. Thank you.

**Comment by jotego** [comment]
Fixed in commit https://github.com/jotego/jtcps1/commit/65328a1b156c1b7b0b1281448c34b32114c4b3b2
