### ISSUE TITLE
CPS1 Missing text in Street Fighter Zero -CPS Changer, Brazil 950727 ?

### ISSUE THREAD

**Issue by Chocobobobo** [jotego/jtbin#64]
Everything checked on 0502 version of the core.
I don't own the original board to check, but it seems odd, so I am posting here, just  in case.
As you can see below, the japanese version has explanations for manual mode
![20200511_015726-screen](https://user-images.githubusercontent.com/23947970/81513832-93c10a00-932b-11ea-8707-cb9e02f016c9.png)
While the brazilian version has an empty box (Auto has text in it)
![20200511_015909-screen](https://user-images.githubusercontent.com/23947970/81513841-a63b4380-932b-11ea-8200-08067d93aec5.png)
Thanks for looking into it!

**Comment by jotego** [comment]
I think they just didn't translate the text. It is not shown in MAME either.

**Comment by Chocobobobo** [comment]
That is super weird, because the text is translated for AUTO. Do you know anyone with the actual board to make it 100% sure? Thanks :)

**Comment by jotego** [comment]
I don't. Maybe it's possible to buy a board from Japanese internet sellers.
