### ISSUE TITLE
Bionic Commando not working anymore Mister :/

### ISSUE THREAD

**Issue by odiaboeeu** [jotego/jtbin#69]
Hello Jotego, I noticed that Bionic Commando is no longer working on the latest version of the mister menu, do not know if you forgot to update his sys or if you are encountering any problems :/ 

Another thing if you could add the Option of H and V sync both on it and in DD1 and DD2 too :D

 Sorry for the bother :3

**Comment by jotego** [comment]
Look at this https://github.com/jotego/jt_gng/issues/52
