### ISSUE TITLE
Bionic Commando.mra starts with only a black screen.

### ISSUE THREAD

**Issue by joxheaf21** [jotego/jtbin#86]
Seems like mra and rbf is not in sync.
If the switches and buttons sections are removed from the mra it works fine.

I suspect that the dips and buttons are for a rbf not yet released. :)

**Comment by jotego** [comment]
The RBF that supports that MRA hasn't been released yet. I have reverted the MRA to the old format in https://github.com/jotego/jtbin/commit/f4c1304d842459a497336d8b703f1643e1f932af
it should be ok now
