### ISSUE TITLE
Black Tiger sometimes freeze.

### ISSUE THREAD

**Issue by Akaifutari** [jotego/jtbin#9]
Hi!
Sometimes, when I play Black Tiger's core the game freeze after the Game Over screen. It occurs sometimes, not always.
My MiSTer have 128mb.
I drop you a pic.

[![IMG-20200209-121652.jpg](https://i.postimg.cc/x8xR5Ch5/IMG-20200209-121652.jpg)](https://postimg.cc/bSnkNzzS)

**Comment by jotego** [comment]
I think this is the same as this is other [issue](https://github.com/jotego/jt_gng/issues/41). Please try today's update as I have improved the SDRAM robustness. I'll close this one and keep track on the other thread.

**Comment by jotego** [comment]
That's sad news. There is something else getting in the way of the Z80 then. Do you have the impression that the latest version is more robust or do you think it didn't make a difference?

**Comment by Chocobobobo** [comment]
Let me hammer the latest rbf more, and I will post an update here after completing Black Tiger and Black Dragon a few more times.
