### ISSUE TITLE
Black Tiger - Hangs

### ISSUE THREAD

**Issue by Hewhoisred** [jotego/jtbin#91]
Still freezing immediately after a boss, on the most recent version of the core:
![2020-06-08](https://user-images.githubusercontent.com/47957258/84078305-8e3bfb80-a98d-11ea-88e9-86bd4113a992.png)
I've seen it happen (or not) after any boss after level 3.  The screenshot is from after the level 4 boss.

**Comment by jotego** [comment]
This is the same as issue https://github.com/jotego/jt_gng/issues/41
I will revisit it soon. For now use bootleg ROMs that don't need the MCU.
I close it here as it is duplicated.
